### ISSUE TITLE
Wget can not fetch source code tarball on official website

### ISSUE THREAD

**Issue by WhiredPlanck** [sonic-visualiser/sonic-visualiser#21]
For example: 
```bash
$ wget https://code.soundsoftware.ac.uk/attachments/download/2580/sonic-visualiser-4.0.tar.gz
```
Get error:
```
Resolving code.soundsoftware.ac.uk (code.soundsoftware.ac.uk)... 138.37.95.184
Connecting to code.soundsoftware.ac.uk (code.soundsoftware.ac.uk)|138.37.95.184|:443... connected.
ERROR: cannot verify code.soundsoftware.ac.uk's certificate, issued by ‘CN=QuoVadis Europe EV SSL CA G1,O=QuoVadis Trustlink B.V.,C=NL’:
  Unable to locally verify the issuer's authority.
To connect to code.soundsoftware.ac.uk insecurely, use `--no-check-certificate'.
```

Please use Intermediate CA on the official website, the CA chain is [incomplete](https://www.ssllabs.com/ssltest/analyze.html?d=code.soundsoftware.ac.uk&latest).

**Comment by cannam** [comment]
Yup. I no longer have any control over this, as I no longer work at the hosting institution. I've reported it upstream but to no effect yet. From the 4.4 release, we will probably stop using this site as the primary download location - switch it to mirror status and use somewhere else (probably Github itself) as the primary.

**Comment by WhiredPlanck** [comment]
> Yup. I no longer have any control over this, as I no longer work at the hosting institution. I've reported it upstream but to no effect yet. From the 4.4 release, we will probably stop using this site as the primary download location - switch it to mirror status and use somewhere else (probably Github itself) as the primary.

I see, thanks for replying.

**Comment by cannam** [comment]
What actually happened for 4.4 is that the SoundSoftware site remains the primary but Github is listed as a mirror, with a recommendation on the download page that people running downloads from scripts (for packaging or whatever) use the Github link. Here's hoping one day the cert gets fixed, but I hope this should be adequate for the mo.
