### ISSUE TITLE
Request: Add key shortcuts for Tools 

### ISSUE THREAD

**Issue by SamuelMiller** [sonic-visualiser/sonic-visualiser#32]
Please consider adding key shortcuts for Tools (Navigate, Select, Edit, Draw, Erase, Measure). I also suggest displaying the shortcut keys with the tool names, when you mouse over them in the toolbar, similar to how shortcuts keys are shown next to "Edit" menu commands.

**Comment by cannam** [comment]
The keys 1-6 on the keyboard (without modifiers) should switch between these?

Adding them to the mouseover text is a good suggestion, although they are listed in the Key & Mouse Reference.

**Comment by SamuelMiller** [comment]
Yup, they work. Thanks. I wasn't aware of the Key & Mouse reference listed under Help. Good to know.
