### ISSUE TITLE
The Steinberg VST3 SDK is dual licensed

### ISSUE THREAD

**Issue by pushytoxin** [sonic-visualiser/sonic-visualiser#37]
Excerpt from the download page:

>VST, AudioUnits? Sonic Visualiser cannot support VST plugins directly because Steinberg's VST license is incompatible with Sonic Visualiser's GPL license.
>Windows and OS/X users can get limited support using the Audacity VST Enabler, and Linux users can try dssi-vst.
>There is no such problem with AudioUnit; we just haven't got around to supporting it yet.

This is misleading. The actual license of VST3 is BSD 3 clause for the public SDK, and dual licensed GPLv3 / Proprietary for the plugin interfaces.

https://github.com/steinbergmedia/vst3sdk

An implementation for a VST3 plugin is therefore possible, if there is an interest.

**Comment by Zipdox** [comment]
Sonic visualizer would have to use the plugin interfaces, which are GPLv3. Sonic Visualiser is GPLv2.
A better idea would be to use LV2 instead.

**Comment by pushytoxin** [comment]
> Sonic Visualiser is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. See the file COPYING included with this distribution for more information.

If someone wishes to implement the plugin interface for VST3 which is GPLv3 they are permitted to publish that version according to the licensing terms as it specifies "GPLv2 or later"

**Comment by cannam** [comment]
I have "solved" the problem by removing the explicatory text from the web page!

Moving SV to GPLv3 just for the sake of VST support I would think is still unlikely, though I'll always agree it would be nice to have broader plugin support.
