### ISSUE TITLE
Sonic Visualiser process won't exit after closing the window

### ISSUE THREAD

**Issue by instr3** [sonic-visualiser/sonic-visualiser#38]
The Sonic Visualiser process does not exit after closing the window when it is still initializing on PC. To reproduce this issue:

1. Install sonic visualiser 4.4, Windows 64 bit version from https://sonicvisualiser.org/download.html
2. Open sonic visualiser. Before the splash window disappears, the main window will show up. Close the main window before the splash window disappears.
3. The splash window will freeze and the sonic visualiser process will not exit automatically. 

It can also be reproduced when "Show splash screen on startup" option is unchecked. To reproduce in this way:

1. Open sonic visualiser. Close it in less than 1 second.
2. The window is closed but the sonic visualiser process remains in the task manager, and will never exit.

Other information:
1. The bug cannot be reproduced on sonic visualiser 4.0 using either method. Did not test on other versions yet.
2. ``stderr`` shows nothing apart from the log ``Document::releaseModel(<none>)`` when this bug happens.

**Comment by instr3** [comment]
I did more tests on my PC and my friend's PC (did not install sv or vamp plugins before ).

The bug can be reproduced on version 4.2 but not on 4.1. Might be related to the update in version 4.2:

 - Speed up startup, especially on Windows and especially when a lot
   of plugins are installed. Plugins are now scanned after the main
   window has been displayed, and the Transform menus are populated
   dynamically when the results are available.

**Comment by cannam** [comment]
I've committed a fix - as often happens, it took a bit of thought but the resulting fix is a one-liner. It'll be in the next release (4.4.1 probably). Thanks for the helpful report, you were quite right about the origin of it.
