### ISSUE TITLE
Unable to export layer

### ISSUE THREAD

**Issue by unchaoss** [sonic-visualiser/sonic-visualiser#41]
Sorry to bother on this low activity forum but I see the Export Annotation Layer greyed out in the attached screenshot.What am I doing wrong?
![Screenshot from 2022-02-05 16-58-18](https://user-images.githubusercontent.com/13725092/152664216-824827e0-e606-45c1-9f9d-d5db1913249a.png)

**Comment by cannam** [comment]
Export Annotation Layer can only export data from layers whose data models are considered to have been calculated or annotated. That does not include the built-in spectrogram or spectrum layers, which are internally considered just to be different visualisations of the audio file model.

I realise this is surprising and likely disappointing - it's quite reasonable to imagine that the built-in spectrograms would be the very easiest thing to export! It may change at some point, but as it stands the historical behaviour is the way it is.
