### ISSUE TITLE
4.5: Unable to build against serd 0.30.14/ sord 0.16.12

### ISSUE THREAD

**Issue by dvzrv** [sonic-visualiser/sonic-visualiser#58]
Hi! I package this software for Arch Linux.

Upon trying to rebuild sonic-visualiser 4.5 against a newer version of capnproto, I was met with issues during linking that are related to serd and/ or sord:

```
[645/649] Linking target piper-vamp-simple-server
FAILED: piper-vamp-simple-server
c++  -o piper-vamp-simple-server piper-vamp-simple-server.p/meson-generated_.._piper.capnp.cpp.o piper-vamp-simple-server.p/piper-vamp-cpp_ext_json11_json11.cpp.o piper-vamp-simple-server.p/piper-vamp-cpp_vamp-server_simple-server.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_PluginBufferingAdapter
.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_PluginChannelAdapter.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_PluginHostAdapter.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_PluginInputDomainAdapter.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vam
p-hostsdk_PluginLoader.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_PluginSummarisingAdapter.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_PluginWrapper.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_src_vamp-hostsdk_RealTime.cpp.o piper-vamp-simple-server.p/vamp-plugin-sdk_s
rc_vamp-hostsdk_Files.cpp.o -flto -Wl,--as-needed -Wl,--no-undefined -pie -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS
 -g -ffile-prefix-map=/build/sonic-visualiser/src=/usr/src/debug -flto=auto -Wl,--start-group /usr/lib/libcapnp.so /usr/lib/libkj.so -pthread /usr/lib/libsord-0.so -ldl -Wl,--end-group
/usr/bin/ld: /usr/lib/libsord-0.so: undefined reference to symbol 'serd_node_from_string'
/usr/bin/ld: /usr/lib/libserd-0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Full build log: 
[sonic-visualiser-4.5-4-x86_64-build.log](https://github.com/sonic-visualiser/sonic-visualiser/files/9459745/sonic-visualiser-4.5-4-x86_64-build.log)

My assumption is, that sonic-visualiser uses a symbol that is now not available anymore. As there has been no soname change in sord or serd (both have been updated from the last time sonic-visualiser has been built though) and the build requirements have not changed in the meantime, I guess this is either a problem with how sonic-visualiser is using serd/sord or how serd/sord updates potentially deprecated internal functionality.

cc @drobilla

**Comment by cannam** [comment]
I ran into this too - it's not a problem with serd/sord, I think, just an omission in the SV build that accidentally worked before. The serd library was never actually specified on the link line. There's a fix in 865fbe253

**Comment by dvzrv** [comment]
Many thanks, will include that!

**Comment by drobilla** [comment]
Yeah, I think meson is a bit different with its pkg-config file philosophy, and the deps there are a bit weird to begin with and different between literal pkg-config and more modern replacements like pkgconf.  I assume meson knows what it's doing and the previous build system was just too lax, but it seems opinions differ on how transitive dependencies should work here, especially when you consider private and/or static dependencies 🤷 

In any case, fix looks good to me.  For the record, there _will_ be a breaking release of serd at some point in the hopefully near future, but that will of course have a new major version number, be possible to install in parallel, and shouldn't break any existing code that uses `serd-0`.
