### ISSUE TITLE
Are there any implementation details of melodic range?

### ISSUE THREAD

**Issue by 980202006** [sonic-visualiser/sonic-visualiser#66]
The feature map of melodic range is very suitable for melody extraction. Is there any implementation details or source code of melodic range spectrogram?

**Comment by cannam** [comment]
The source code is all there in the Sonic Visualiser source packages (which pull together this repo with the `svcore`, `svgui`, `svapp` repos). All of the spectrogram layers (`svgui/layer/SpectrogramLayer.cpp`) have the same code, just different initial starting parameters. The FFT parameters are visible in the settings on the right side of the pane, and the default frequency range, frequency mapping etc are as described [in the SV docs](https://www.sonicvisualiser.org/doc/reference/4.5/en/#spectrogram). The default colour mapping I think is Sunset, which is defined in `svgui/layer/ColourMapper.cpp` lines 324 onward.

The most critical things are

 * 8192-bin FFT for decent frequency resolution
 * 8x overlap for not-too-awful visual time resolution
 * Frequency range c. 40 - 1500 Hz
 * Linear mapping between magnitude and colour
 * Perky colour scale
