### ISSUE TITLE
warping old songs ?

### ISSUE THREAD

**Issue by pascalspits** [sonic-visualiser/sonic-visualiser#68]
I have noticed that the “Queen Mary” tempo and beat tracker is far superior to all other beat marker engines out there, especially for old (manually drummed) songs.

I’ve been looking into Sonic Visualiser, whith the VAMP plugins to detect bars and measures but I can’t find a way to quantize the songs to a steady beat and export them to WAV (or MP3) as such …

I wonder : Is there a way to "quantize" or "warp" this variable detected beat grid for “exporting” these songs into a “tight”, “warped” version with a dead-steady tempo ?

**Comment by cannam** [comment]
Not using Sonic Visualiser, no...

Other interactive tools might be able to do this, I don't know. Perhaps some DAWs might.

It can probably be scripted using a command-line Vamp host (`vamp-simple-host` or Sonic Annotator) and the Rubber Band timestretcher command-line utility which has a time-map mode. For example, [here](https://hg.sr.ht/~cannam/waltz/browse/waltz.sh?rev=tip) is a Bash script that uses those tools to turn 4/4 performances into waltzes.
