### ISSUE TITLE
quick question—disable file info (?) on top-left of spectrogram

### ISSUE THREAD

**Issue by meganlavengood** [sonic-visualiser/sonic-visualiser#87]
what is this and how can I turn it off?

![ss 2024-02-12 at 10 45 06 AM](https://github.com/sonic-visualiser/sonic-visualiser/assets/60526470/839ae633-4653-41b7-ac37-ca68d076c090)

I can turn it off by clicking "show no overlays," but I'd like to keep the keyboard/Hz information on the left.

**Comment by cannam** [comment]
That looks like the selection rectangle extent display, which is only shown when you select something.

The top pair of numbers is the start time of the selection, in seconds and audio sample frames respectively. The bottom one (in brackets) is the duration of the selection, similarly. At the other end of the selection there's a corresponding display of the end time and duration.

There isn't any way to get rid of these while retaining the vertical scale, other than by clearing the selection (Esc or equivalent).

**Comment by meganlavengood** [comment]
Esc was what I needed—thanks for the quick response!
