### ISSUE TITLE
OSC not available with default build

### ISSUE THREAD

**Issue by alefz3r0** [sonic-visualiser/sonic-visualiser#9]
Hi, sorry for opening an issue here, but I couldn't find help in the manual.

I want to use OSC commands, but it seems OSC is not running. In the help->about menu i get "" instead of the URL

I am using the default build for windows 64bit downloaded from the site, version 4.0.1
Do I have to compile from scratch with the liblo OSC library? Or am I doing something wrong?

Many thanks for the great work though!

**Comment by alefz3r0** [comment]
Actually resolved, since I found in a forum thread that liblo OSC library is not working on Windows.

I solved by running the AppImage version on the Ubuntu shell in windows by installing the Linux subsystem for windows component

**Comment by cannam** [comment]
It's true that neither 32- nor 64-bit Windows build has OSC support enabled, and that you would have to use one of the Linux or Mac builds.

I might have another look at liblo and see if I can either get it built or reassure myself that it's not possible - it would be quite nice to have this. Depending on time available.
