### ISSUE TITLE
On Version 5.0.0, Analysis settings' Spectrum mode cannot be changed.

### ISSUE THREAD

**Issue by Valentine-Zwe** [sonic-visualiser/sonic-visualiser#97]
The "Apply" button does not seem to work, and the "OK" button also does not make the changes.
EDIT to add: Additionally, the Apply button is not able to be selected. I have tried pressing tab through the buttons, which would skip said Apply button.

![This is the preference setting that I am having difficulties with.](https://github.com/user-attachments/assets/5608dc58-1e71-4cbc-8264-8562c80d6bf6)

**Comment by cannam** [comment]
Thanks! It was a Qt signal/slot mismatch. Fixed in the repo, by switching to the newer type-safe connection syntax. I'll aim to do a minor release shortly.

**Comment by Valentine-Zwe** [comment]
This is fixed now in 5.0.1 as per the changelog. I can do the relevant changes now. Thanks again!

Would you like me to close this issue myself, or will you do it?

**Comment by cannam** [comment]
I can, thanks for the feedback!
